config/routes.rb
Rails.application.routes.draw do
  resources :msgs
  get 'chat' => 'msgs#chatpage'
  root 'msgs#chatpage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/msg.rb
class Msg < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/msgs_controller.rb
class MsgsController < ApplicationController
  before_action :set_msg, only: [:show, :edit, :update, :destroy]

  # GET /msgs
  # GET /msgs.json
  def index
    @msgs = Msg.all
    newhash = DateTime.strptime("1318996912",'%s')
    @namehash = Digest::SHA1.hexdigest(newhash)
  end

  # GET /msgs/1
  # GET /msgs/1.json
  def show
  end

  # GET /msgs/new
  def new
    @msg = Msg.new
  end

  # GET /msgs/1/edit
  def edit
  end

  # POST /msgs
  # POST /msgs.json
  def create
    message = msg_params
    @msg = Msg.new(msg_params)
    thesender = @msg.sender
    thesentdate = @msg.sent
    theservertime = DateTime.now
    unless @msg.content.empty? || @msg.sender.empty?
      ActionCable.server.broadcast 'room_channel',
                                   content: @msg.content,
                                   sender: thesender,
                                   servertime: theservertime
    end
  end

  # PATCH/PUT /msgs/1
  # PATCH/PUT /msgs/1.json
  def update
    respond_to do |format|
      if @msg.update(msg_params)
        format.html { redirect_to @msg, notice: 'Msg was successfully updated.' }
        format.json { render :show, status: :ok, location: @msg }
      else
        format.html { render :edit }
        format.json { render json: @msg.errors, status: :unprocessable_entity }
      end
    end
  end

  def chatpage
    @msg = Msg.new
    @nmh = [*('a'..'z'),*('0'..'9')].shuffle[0,8].join
  end

  # DELETE /msgs/1
  # DELETE /msgs/1.json
  def destroy
    @msg.destroy
    respond_to do |format|
      format.html { redirect_to msgs_url, notice: 'Msg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_msg
      @msg = Msg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def msg_params
      params.require(:msg).permit(:content, :sender, :sent, :sent_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/msgs_helper.rb
module MsgsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeyak</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<!-- Codeyak chat site by Dan McKeown http://danmckeown.info copyright April 2017  -->
  <body>
    <%= yield %>
  </body>
</html>

app/views/msgs/_form.html.erb
<%= form_for(msg) do |f| %>
  <% if msg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(msg.errors.count, "error") %> prohibited this msg from being saved:</h2>

      <ul>
      <% msg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :sender %>
    <%= f.text_field :sender %>
  </div>

  <div class="field">
    <%= f.label :sent %>
    <%= f.date_select :sent %>
  </div>

  <div class="field">
    <%= f.label :sent_id %>
    <%= f.text_field :sent_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/msgs/chatpage.html.erb
<div id="ctnr" class="container">
  <div id="msg_content" class="content-holder">
    <span id="main_msg_title" class="content-span">
    </span>
    <span id="description"> a <a href="http://codeyak.pacificio.com" class="pacificiolink">programming chat site</a> from <a id="author-link" class="credits" href="http://danmckeown.info">Dan McKeown</a>
    </span>
  </div>
<div id="rform">
  <%= form_for @msg do |f| %>
    <span id="sender">sender:</span><%= f.text_field :sender, :value => @nmh %><br />
    <%= f.text_area :content %>
    <br />
    <span id="sbutton">
      <input type="submit" name="commit" value="Create Msg" />
    </span>
    <br />
    <span id="codeYakLogo">
      <%= image_tag 'codeYak.jpg' %>
    </span>
  <% end %>
</div> <!-- end of div#cntr -->
</div>

app/views/msgs/edit.html.erb
<h1>Editing Msg</h1>

<%= render 'form', msg: @msg %>

<%= link_to 'Show', @msg %> |
<%= link_to 'Back', msgs_path %>

app/views/msgs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Msgs</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Sender</th>
      <th>Sent</th>
      <th>Sent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @msgs.each do |msg| %>
      <tr>
        <td><%= msg.content %></td>
        <td><%= msg.sender %></td>
        <td><%= msg.sent %></td>
        <td><%= msg.sent_id %></td>
        <td><%= link_to 'Show', msg %></td>
        <td><%= link_to 'Edit', edit_msg_path(msg) %></td>
        <td><%= link_to 'Destroy', msg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Msg', new_msg_path %>

app/views/msgs/new.html.erb
<h1>New Msg</h1>

<%= render 'form', msg: @msg %>

<%= link_to 'Back', msgs_path %>

app/views/msgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @msg.content %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @msg.sender %>
</p>

<p>
  <strong>Sent:</strong>
  <%= @msg.sent %>
</p>

<p>
  <strong>Sent:</strong>
  <%= @msg.sent_id %>
</p>

<%= link_to 'Edit', edit_msg_path(@msg) %> |
<%= link_to 'Back', msgs_path %>